
export const INCREMENT_AGE = 'INCREMENT_AGE';
export type INCREMENT_AGE_TYPE = typeof INCREMENT_AGE;

export const DECREMENT_AGE = 'DECREMENT_AGE';
export type DECREMENT_AGE_TYPE = typeof DECREMENT_AGE;
